"""updateQuizTable

Revision ID: d01dfb89238e
Revises: 051024403f17
Create Date: 2023-03-24 14:04:58.824833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01dfb89238e'
down_revision = '051024403f17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('quiz_id', sa.Integer(), nullable=False), schema='lqs')
    op.create_foreign_key(None, 'responses', 'quizzes', ['quiz_id'], ['id'], source_schema='lqs', referent_schema='lqs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', schema='lqs', type_='foreignkey')
    op.drop_column('responses', 'quiz_id', schema='lqs')
    # ### end Alembic commands ###
